/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: (typeof import('./src/components/loadingComponent copy.vue'))['default']
    DefineAsyncComponent: (typeof import('./src/components/defineAsyncComponent.vue'))['default']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    ElText: (typeof import('element-plus/es'))['ElText']
    ErrorComponent: (typeof import('./src/components/errorComponent.vue'))['default']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    LoadingComponent: (typeof import('./src/components/loadingComponent.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
